#pragma once

#include <cstdint>

enum hiprtc_test_counter {
    HIPRTC_TEST_CREATE,
    HIPRTC_TEST_COMPILE,
    HIPRTC_TEST_LOAD,
    HIPRTC_TEST_UNLOAD,
    HIPRTC_TEST_MODULE_LAUNCH,
    HIPRTC_TEST_CAPTURE_BEGIN,
    HIPRTC_TEST_CAPTURE_END,
    HIPRTC_TEST_GRAPH_LAUNCH,
    HIPRTC_TEST_RESOURCE_QUERY,
    HIPRTC_TEST_ALLOCATE,
    HIPRTC_TEST_VERSION,
    HIPRTC_TEST_SETUP_DURING_CAPTURE,
    HIPRTC_TEST_EVENT_RECORD,
    HIPRTC_TEST_STREAM_WAIT,
    HIPRTC_TEST_LOAD_NS,
    HIPRTC_TEST_COUNTER_COUNT,
};

extern "C" void hiprtc_test_snapshot(uint64_t * counters);
